AzkatechApplication/AzkatechApplication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("main.urls", "main"), namespace="main")),
]

AzkatechApplication/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("home/", views.home, name="home"),
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("", views.login_request, name="login"),
    path("logout/", views.logout_request, name= "logout"),
    path("add/", views.add, name= "add"),
    path('update/<int:pk>/', views.VacationUpdate, name='vac_update'),
    path('delete/<int:pk>/', views.VacationDelete, name='vac_delete'),
]

AzkatechApplication/main/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from django.forms import ModelForm

# Create your models here.
class Vacation(models.Model): #This is the vacation model with fields as required by the exercise.
    description = models.CharField(max_length=300, default="none")
    start_date = models.DateField(default=datetime.datetime.now)
    end_date = models.DateField(default=datetime.datetime.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="vacation")
    def __str__(self):
        return self.description
#complete = models.BooleanField()

AzkatechApplication/main/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Vacation
# Create your forms here.

class DateInput(forms.DateInput): #Used for the Calendar UI
    input_type = 'date'

class NewUserForm(UserCreationForm): #Used for the user creation form
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class VacationForm(forms.ModelForm): #Used to add/edit vacations
    class Meta:
        model = Vacation
        exclude=['user'] #No need for user field when adding as user is already logged in.
        widgets = {
        	'start_date' : DateInput(), #Calendar UI
        	'end_date' : DateInput(), #Calendar UI
        }

AzkatechApplication/main/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.shortcuts import  render, redirect
from .forms import NewUserForm, VacationForm
from django.contrib.auth import login
from django.contrib import messages #import messages
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .models import Vacation
# Create your views here.

def home(response):
    vacation = Vacation.objects.filter(user=response.user) #displaying vacations of specific user
    return render(response, "main/home.html", locals())

def add(request):
    if not request.user:
        return redirect('/login')
    form = VacationForm()
    if request.method=="POST":
        form = VacationForm(data=request.POST)
        if form.is_valid():
            submission = form.save(commit=False)
            submission.user = request.user #I did this to save the data under the user that is logged in.
            submission.save()
            return redirect('/home')
    return render(request, 'main/add.html', locals())

def register_request(request): #This displays a form to create a new user
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, 'Registration successful.')
			return redirect("/home")
		messages.error(request, 'Unsuccessful registration. Invalid information.')
	form = NewUserForm
	return render (request=request, template_name="main/register.html", context={"register_form":form})

def login_request(request): #This is the login form
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, 'You are now logged in as {username}.')
                return redirect("/home")
            else:
                messages.error(request,'Invalid username or password.')
        else:
            messages.error(request,'Invalid username or password.')
    form = AuthenticationForm()
    return render(request=request, template_name="main/login.html", context={"login_form":form})

def logout_request(request): #Logging out
    logout(request)
    messages.info(request, 'You have successfully logged out.') 
    return redirect("/login")

def VacationUpdate(request, pk): #This is for editing an existing vacation, by filling in the form already with info using the appropriate ID, then altering it when a user makes a change.
    if not request.user:
        return redirect('/login')
    obj = Vacation.objects.get(id=pk)
    form = VacationForm(instance=obj)
    if request.method == 'POST':
        form = VacationForm(data=request.POST, instance=obj)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            return redirect('/home')
    return render(request, 'main/add.html', locals())

def VacationDelete(request, pk): #This simply deletes the row of the appropriate ID.
    if not request.user:
        return redirect('/login')
    obj = get_object_or_404(Vacation, id=pk)
    obj.delete()
    return redirect('/home')

AzkatechApplication/main/templates/main/add.html
{% extends 'main/base.html' %}
{% block title %} 
Home 
{% endblock %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}                    
		<button class="btn btn-primary" type="submit">Add</button>
	</form>
</div>

{% endblock %}

AzkatechApplication/main/templates/main/base.html
<!doctype html>
<html>

<head>
    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Azkatech</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link" href="#">Welcome, {{user.username}}</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/home">Home</a> </li>

            <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="/login">Login</a>
            </li>

            {% endif %}
        </ul>
    </div>
</nav>

<body>
    <div id="content" , name="content"></div>
    {% block content %} {% endblock %}

    <!--Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

AzkatechApplication/main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %} 
Home 
{% endblock %}

{% block content %}
{% for vac in user.vacation.all %}
    <ul>
        <li>
        {{vac.description}}
        <ul>
            <li>
            {{vac.start_date}}
            </li>
            <li>
            {{vac.end_date}}
            </li>
            <li>
            Vacation Duration: {{ vac.end_date|timeuntil:vac.start_date }}
            </li>
            <li>
            <a href="{% url 'main:vac_delete' pk=vac.id%}"><button>Delete Vacation</button></a>
            <a href="{% url 'main:vac_update' pk=vac.id%}"><button>Edit Vacation</button></a>
            </li>
        </ul>
    </ul>
{% endfor %}
  <a href="/add"><button>Add New Vacation</button></a>
{% endblock %}

AzkatechApplication/main/templates/main/login.html
{% extends "main/base.html" %}

{% block content %}      

{% load crispy_forms_tags %}
<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

{% endblock %}

AzkatechApplication/main/templates/main/register.html
{% extends "main/base.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}